name: checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mypy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install mypy
      run: |
        pip install --upgrade pip
        pip install mypy
        mypy --version

    - name: Install dependencies
      run: pip install typing-extensions

    - name: Run mypy
      run: mypy --python-version ${{ matrix.python-version }} -p hid_parser


  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.0
