name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up target Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install nox
        run: |
            pip install nox
            nox --version

      - name: Run tests
        run: nox -s test-${{ matrix.python-version }}

      - name: Send coverage report
        uses: codecov/codecov-action@v3
        env:
          PYTHON: ${{ matrix.python-version }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: PYTHON
